// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFRvo1qUhsvDZTRWjnXZ3iINnsvm7Eorc',
    appId: '1:1047781395913:web:c222ebd4992f98e956ac18',
    messagingSenderId: '1047781395913',
    projectId: 'ecosync-ba204',
    authDomain: 'ecosync-ba204.firebaseapp.com',
    storageBucket: 'ecosync-ba204.appspot.com',
    measurementId: 'G-XFBJYV2FR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5JxujnKr9FUeqkxGk2I2xnSqnBexkWo',
    appId: '1:1047781395913:android:a43c37700e52a17e56ac18',
    messagingSenderId: '1047781395913',
    projectId: 'ecosync-ba204',
    storageBucket: 'ecosync-ba204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb7RXNzMr_zA38MiNStUKGhvBzFl2SIXw',
    appId: '1:1047781395913:ios:b3bc0cb297eb07c556ac18',
    messagingSenderId: '1047781395913',
    projectId: 'ecosync-ba204',
    storageBucket: 'ecosync-ba204.appspot.com',
    iosBundleId: 'com.example.ecosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb7RXNzMr_zA38MiNStUKGhvBzFl2SIXw',
    appId: '1:1047781395913:ios:b3bc0cb297eb07c556ac18',
    messagingSenderId: '1047781395913',
    projectId: 'ecosync-ba204',
    storageBucket: 'ecosync-ba204.appspot.com',
    iosBundleId: 'com.example.ecosync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFRvo1qUhsvDZTRWjnXZ3iINnsvm7Eorc',
    appId: '1:1047781395913:web:20ae2e064044895756ac18',
    messagingSenderId: '1047781395913',
    projectId: 'ecosync-ba204',
    authDomain: 'ecosync-ba204.firebaseapp.com',
    storageBucket: 'ecosync-ba204.appspot.com',
    measurementId: 'G-V48RX6G2T1',
  );
}
